### PR TITLE
Merged CollectionsEditorBehaviour and RegistryEditorBehaviour

### PR DESCRIPTION
**Pull request by ovieira**
I found this issue on some specific scenarios where you manually delete a collection from the project.

This should fix a racing condition where having a missing reference in the collections registry throws a null reference when calling the PrepareForPlayMode. 

This is mainly because I don't see a way of forcing the CollectionsEditorBehavior to run before the RegistryEditorBehavior. 

By making sure the reload collection is called first, the issue should cease to exist.

### CODE REVIEW

**Comment by ovieira** [comment]
I though about merging both classes @brunomikoski , but considering the issue, if you see a better solution please let me know :)

**Review by brunomikoski — APPROVED** [review]

**Comment by brunomikoski** [comment]
Sounds good to me! 
Coul you please add a quick summary of the changes on the `CHANGELOG.MD` on the unreleased part please?

**Comment by ovieira** [comment]
> Sounds good to me! Coul you please add a quick summary of the changes on the `CHANGELOG.MD` on the unreleased part please?

Sure!

Also, an additional note. You use "PlayModeStateChange.ExitingPlayMode" on one class and "PlayModeStateChange.EnteredEditMode" on the other. Is there any reasoning for this?  Because my merging, I'm only using the EnteredEditMode to trigger the reload

**Comment by brunomikoski** [comment]
> > Sounds good to me! Coul you please add a quick summary of the changes on the `CHANGELOG.MD` on the unreleased part please?
> 
> Sure!
> 
> Also, an additional note. You use "PlayModeStateChange.ExitingPlayMode" on one class and "PlayModeStateChange.EnteredEditMode" on the other. Is there any reasoning for this? Because my merging, I'm only using the EnteredEditMode to trigger the reload

I will take a closer look to see if there's any clear reason why they are appart! But don't worry about it now! Feel free to merge your PR :D 

and thanks!

**Pull request merged**
